Homework 4
polisgo2020/search-bolotrush pull request #5
Opened 2020-04-16 09:34 UTC by bolotrush

2020-04-21 20:43 UTC, tariel-x requested changes

2020-04-21 20:43 UTC, tariel-x commented on README.md
> +* `-web` - запуск сервера по адресу `localhost:8080`, который принимает http GET запрос, содержащий поисковую фразу и возвращает список подходящих документов
Это неправда, потому что
```
// For TCP networks, if the host in the address parameter is empty or
// a literal unspecified IP address, Listen listens on all available
// unicast and anycast IP addresses of the local system.
```

2020-04-21 20:43 UTC, tariel-x commented on main.go
> +		web.RunServer(":8080", InvertedIndexMap)
В задании было сказано, что этот параметр нужно получать из аргументов.

2020-04-21 20:43 UTC, tariel-x commented on web/web.go
> +	log.Fatal(server.ListenAndServe())
Было бы правильней возвращать здесь ошибку, которую обрабатывать в main.

2020-04-21 20:43 UTC, tariel-x commented on web/web.go
> +	fmt.Println("starting server at", addr)
Если ниже log, то почему здесь fmt.

2020-04-21 20:43 UTC, tariel-x commented on web/web.go
> +		fmt.Println("There's no results :(")
Для кого именно этот лог?

2020-04-21 20:43 UTC, tariel-x commented on web/web.go
> +			_, err := fmt.Fprintf(w, "%d) %s: matches - %d\n", i+1, match.FileName, match.Matches)
Можно объеденить в одну строку с if.

2020-04-21 20:43 UTC, tariel-x commented on web/web.go
> +				return
Если произойдёт ошибка, о ней никто никогда не узнает.

2020-04-21 20:43 UTC, tariel-x commented on main.go
> +		log.Fatal(errors.New("path to files is incorrect"))
Эту ошибку следовало бы генерировать внутри функции textBuilder, потому что textBuilder явно делает больше операций, чем просто читает файлы.

2020-04-21 20:43 UTC, tariel-x commented on index/index.go
> +		input.Mutex.Lock()
Вообще, касательно предыдущего ДЗ, не понятно, почему этот мьютекс передаётся с этой структурой. Почему бы не сделать InvMap структурой, в которой будет непосредственно индекс и мьютекс и канал. Тогда их не нужно будет создавать снаружи и код будет выглядеть красивее.

2020-04-21 20:43 UTC, tariel-x commented on index/index.go
> +func ShowSearchResults(matchListOut []MatchList) {
Кажется, что эта функция должна быть в main, а не в index.

2020-04-23 12:31 UTC, bolotrush commented on main.go
> +		web.RunServer(":8080", InvertedIndexMap)
Исправил, теперь порт принимается с флагом -web

2020-04-23 12:32 UTC, bolotrush commented on web/web.go
> +	log.Fatal(server.ListenAndServe())
Исправил

2020-04-23 12:32 UTC, bolotrush commented on web/web.go
> +	fmt.Println("starting server at", addr)
Исправил

2020-04-23 12:32 UTC, bolotrush commented on web/web.go
> +		fmt.Println("There's no results :(")
Выводит на страницу, исправил

2020-04-23 12:32 UTC, bolotrush commented on web/web.go
> +			_, err := fmt.Fprintf(w, "%d) %s: matches - %d\n", i+1, match.FileName, match.Matches)
Убрал if просто, пусть выводит все результаты

2020-04-23 12:32 UTC, bolotrush commented on web/web.go
> +				return
Исправил

2020-04-23 12:32 UTC, bolotrush commented on main.go
> +		log.Fatal(errors.New("path to files is incorrect"))
Исправил

2020-04-23 12:32 UTC, bolotrush commented on index/index.go
> +		input.Mutex.Lock()
Понял вас, попробую переделать, скину уже с 6 домашкой тогда

2020-04-23 12:35 UTC, bolotrush commented on index/index.go
> +func ShowSearchResults(matchListOut []MatchList) {
Перенес

2020-04-24 01:52 UTC, tariel-x approved these changes
:+1: 

конфликты только исправить

2020-04-24 14:01 UTC, merged